# Generated by Django 5.1.3 on 2024-11-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0004_acompanhantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanhantes',
        ),
    ]
