# Generated by Django 5.1.3 on 2024-11-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0005_delete_acompanhantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidados',
            name='maximo_acompanhantes',
        ),
    ]
